// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (*Accounts, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (*Accounts, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]*Accounts, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (*Accounts, error)
}

var _ Querier = (*Queries)(nil)
